#ifndef MYKERNEL_GPIO_DEFS_H
#define MYKERNEL_GPIO_DEFS_H

#define GPIO_FUNCTION_IN   (0b000)
#define GPIO_FUNCTION_OUT  (0b001)
#define GPIO_FUNCTION_ALT0 (0b100)
#define GPIO_FUNCTION_ALT1 (0b101)
#define GPIO_FUNCTION_ALT2 (0b110)
#define GPIO_FUNCTION_ALT3 (0b111)
#define GPIO_FUNCTION_ALT4 (0b011)
#define GPIO_FUNCTION_ALT5 (0b010)

#define GPIO_PULL_NONE (0)
#define GPIO_PULL_DOWN (2)
#define GPIO_PULL_UP   (1)

#endif
