#ifndef MYKERNEL_REGS_H
#define MYKERNEL_REGS_H

#include "defs.h"

typedef u64 reg_addr_t;

enum
{
    PERIPHERAL_BASE = 0xfe000000ULL,
    
    // GPIO

    GPIO_BASE = PERIPHERAL_BASE + 0x200000,

    GPIO_GPFSEL0 = GPIO_BASE + 0x00,
    GPIO_GPFSEL1 = GPIO_BASE + 0x04,
    GPIO_GPFSEL2 = GPIO_BASE + 0x08,
    GPIO_GPFSEL3 = GPIO_BASE + 0x0c,
    GPIO_GPFSEL4 = GPIO_BASE + 0x10,
    GPIO_GPFSEL5 = GPIO_BASE + 0x14,
    
    GPIO_GPSET0 = GPIO_BASE + 0x1c,
    GPIO_GPSET1 = GPIO_BASE + 0x20,
    
    GPIO_GPCLR0 = GPIO_BASE + 0x28,
    GPIO_GPCLR1 = GPIO_BASE + 0x2c,

    GPIO_GPLEV0 = GPIO_BASE + 0x34,
    GPIO_GPLEV1 = GPIO_BASE + 0x38,

    GPIO_PUP_PDN_CNTRL_REG0 = GPIO_BASE + 0xe4,
    GPIO_PUP_PDN_CNTRL_REG1 = GPIO_BASE + 0xe8,
    GPIO_PUP_PDN_CNTRL_REG2 = GPIO_BASE + 0xec,
    GPIO_PUP_PDN_CNTRL_REG3 = GPIO_BASE + 0xf0,

    // System Timer

    SYSTEM_TIMER_BASE = PERIPHERAL_BASE + 0x003000,

    SYSTEM_TIMER_CS = SYSTEM_TIMER_BASE + 0x00,
    SYSTEM_TIMER_CLO = SYSTEM_TIMER_BASE + 0x04,
    SYSTEM_TIMER_CHI = SYSTEM_TIMER_BASE + 0x08,
};

#define REG(reg) (*(volatile uint*) (reg))

#endif
